### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by andrewrunxiyu** [beagleboard/beaglebone-black#14]
What license are the design files under?

I'm looking into if this qualifies as free hardware as defined by the [Free Computing Movement](https://fcm.andrewyu.org) (which is basically me for now...).

If you guys are thinking, maybe GPL v3 or CERN 2.0 (strong copyleft)?

**Comment by mikini** [comment]
Based on [the reference to the board's OSHWA certification](https://github.com/beagleboard/beaglebone-black/blob/master/README.md) and link to [its OSHWA project page](https://certification.oshwa.org/us000236.html) I would say the license is "CC BY-SA 3.0".

Also, there are some additional wording [in the SRM about the design files](https://github.com/beagleboard/beaglebone-black/wiki/System-Reference-Manual#beaglebone-design).

Interesting to learn about the FCM. As a hardware engineer I've sometimes been puzzled by the FSF's position on hardware. I know that hardware freedom is just as empowering as software freedom. Will have a look at your page.
