### ISSUE TITLE
Wrong connector number in SRM

### ISSUE THREAD

**Issue by smortex** [beagleboard/beaglebone-black#3]
On page 85 of file `BBB_SRM.pdf`, Rev C.1, we can read:

* “# Both of these signals connect to pin 41 of P*11*.”
* “@ Both of these signals connect to pin 42 of P*11*.”

But there is no P*11* connector.  In fact, this is the section talking about P*9* so **P11** should be replaced by **P9**.

**Comment by smortex** [comment]
Same paragraphs, “by removing R*221*.” and “by removing R*202*.”.

There are no R*202* / R*221*. As far as I understand, **R221** should be **R20**, and **R202** should be **R51**.  But one may prefer to remove R20 and R50 depending on the application… maybe it makes sense to tell the user about the 3 possibilities (use one pin as input, the other one as output ; remove one of the resistors ; remove the other resistor).

**Comment by jadonk** [comment]
@smortex thanks!

Note that the latest SRM is now at https://github.com/beagleboard/beaglebone-black/wiki/System-Reference-Manual. I'm still working on the process of producing a suitable new .PDF file to replace BBB_SRM.pdf.

**Comment by jadonk** [comment]
Updated on wiki: https://github.com/beagleboard/beaglebone-black/wiki/System-Reference-Manual/_compare/363d5c354752fb1a1734f4a465a1d885d3a89e16...0828a11554c69e32f2dd45afb77fd1157a17b44d

**Comment by jadonk** [comment]
Note I've duplicated and expanded upon some of this table data at https://github.com/beagleboard/capes

**Comment by jadonk** [comment]
OK, I think I've fixed it up enough.
