### ISSUE TITLE
P10 (SD Card Slot) Obsolete

### ISSUE THREAD

**Issue by abferm** [beagleboard/beaglebone-black#6]
ALPS has discontinued SCHA5B0200 without an alternative or replacement. If there is a suitable replacement from a different manufacturer the BOM should be updated.

`P10	Connector SD/MMC	ALPS	SCHA5B0200`

> Dear Alex Ferm,
> 
>  
> 
> Thank you for your interest in Alps Electric.
> 
>  
> 
> With regard to your inquiry, we apologize but Alps discontinued all card connectors with no replacements or alternatives.
> 
>  
> 
>  
> 
> Best regards,
> 
>  
> 
> Lourdes Olanio
> 
> Sales Representative
> 
> Alps Electric (North America), Inc.

**Comment by jadonk** [comment]
No suitable replacment has been found. They continue to supply this component. We did a design update with a new card cage, but it didn't pass FCC/CE and we currently have no plans to revisit. We continue to be able to design in high volume (~400k/yr).

**Comment by jadonk** [comment]
Alternate proposed SD card cage options with associated layout update are:
* Molex 5027740891
* XUNPU TF-114

**Comment by jadonk** [comment]
Resolved in rev_c3
