### ISSUE TITLE
Beaglebone black boot kernel panic

### ISSUE THREAD

**Issue by natasha323** [beagleboard/beaglebone-black#7]
Hi, i have a problem with BBB.

I have two sd images and both worked fine.
Then during work it disconnected from PC, i tried to reboot it, but reboot fails with this log with both sd cards:

U-Boot SPL 2013.04-dirty (Jul 10 2013 - 14:02:53)
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Peripheral mode controller at 47401000 using PIO, IRQ 0
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Host mode controller at 47401800 using PIO, IRQ 0
OMAP SD/MMC: 0
mmc_send_cmd : timeout: No status update
reading u-boot.img
reading u-boot.img

U-Boot 2013.04-dirty (Jul 10 2013 - 14:02:53)

I2C:   ready
DRAM:  512 MiB
WARNING: Caches not enabled
NAND:  No NAND device found!!!
0 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
*** Warning - readenv() failed, using default environment

musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Peripheral mode controller at 47401000 using PIO, IRQ 0
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Host mode controller at 47401800 using PIO, IRQ 0
Net:   <ethaddr> not set. Validating first E-fuse MAC
Phy not found
PHY reset timed out
cpsw, usb_ether
Hit any key to stop autoboot:  0 
gpio: pin 53 (gpio 53) value is 1
mmc0 is current device
micro SD card found
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
SD/MMC found on device 0
reading uEnv.txt
33 bytes read in 4 ms (7.8 KiB/s)
Loaded environment from uEnv.txt
Importing environment from mmc ...
gpio: pin 55 (gpio 55) value is 1
4381184 bytes read in 816 ms (5.1 MiB/s)
gpio: pin 56 (gpio 56) value is 1
24238 bytes read in 55 ms (429.7 KiB/s)
Booting from mmc ...
## Booting kernel from Legacy Image at 80007fc0 ...
   Image Name:   Linux-3.8.13
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4381120 Bytes = 4.2 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 80f80000
   Booting using the fdt blob at 0x80f80000
   XIP Kernel Image ... OK
OK
   Using Device Tree in place at 80f80000, end 80f88ead

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
[    0.190418] omap2_mbox_probe: platform not supported
[    0.200964] tps65217-bl tps65217-bl: no platform data provided
[    0.276307] omap_hsmmc mmc.5: of_parse_phandle_with_args of 'reset' failed
[    0.340932] pinctrl-single 44e10800.pinmux: pin 44e10854 already requested by 44e10800.pinmux; cannot claim for gpio-leds.8
[    0.352646] pinctrl-single 44e10800.pinmux: pin-21 (gpio-leds.8) status -22
[    0.359960] pinctrl-single 44e10800.pinmux: could not request pin 21 on device pinctrl-single
[    0.464476] Unhandled fault: external abort on non-linefetch (0x1008) at 0xe09e2000
[    0.472492] Internal error: : 1008 [#1] SMP THUMB2
[    0.477498] Modules linked in:
[    0.480701] CPU: 0    Not tainted  (3.8.13 #12)
[    0.485448] PC is at cpsw_probe+0x3ee/0x88c
[    0.489840] LR is at ioremap_page_range+0xad/0xe8
[    0.494761] pc : [<c0250e16>]    lr : [<c019f111>]    psr: 80000133
[    0.494761] sp : df051e20  ip : e09e4000  fp : df3c6590
[    0.506753] r10: df3784a0  r9 : 00000000  r8 : df10d800
[    0.512214] r7 : df10d810  r6 : e09e2000  r5 : df3c6540  r4 : df3c6000
[    0.519033] r3 : 00000000  r2 : 00000800  r1 : c0250e03  r0 : e09e2000
[    0.525855] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA Thumb  Segment kernel
[    0.533674] Control: 50c5387d  Table: 80004019  DAC: 00000015
[    0.539678] Process swapper/0 (pid: 1, stack limit = 0xdf050240)
[    0.545954] Stack: (0xdf051e20 to 0xdf052000)
[    0.550517] 1e20: 00000000 c06a7440 00000001 df3c6298 df04cac0 df3c9548 00000000 df051e88
[    0.559069] 1e40: df10c408 c00d0f2f 22222222 df3c9548 df3cae40 df3c9548 df051e88 c00d0e77
[    0.567620] 1e60: df04cac0 df3c9548 df3c9548 00000000 df3c95c8 c00d1557 df0474b8 c004184d
[    0.576171] 1e80: 00000000 00000003 00000008 00000020 df10d844 df10d810 df10d844 c072b1fc
[    0.584722] 1ea0: c072b204 c06beb18 00000000 00000000 00000000 c0201597 c020158b c0200b37
[    0.593272] 1ec0: 00000000 df10d810 df10d844 c06beb18 00000000 c06d9d80 00000000 c0200c45
[    0.601823] 1ee0: c06beb18 c0200c15 00000000 c01ffd5f df047478 df104580 c06beb18 df3cae40
[    0.610375] 1f00: c06b5380 c02005d1 c054e5f7 c054e5f8 c06beb18 c064e048 c064e028 c0644ffd
[    0.618926] 1f20: c06d9d80 c0201025 00000007 c064e048 c064e028 c0644ffd c06d9d80 00000000
[    0.627477] 1f40: 00000000 c0008661 00000007 00000007 c06a27e0 00000007 c064e044 00000007
[    0.636028] 1f60: c064e048 c064e028 c06d9d80 000000f6 c0660134 c062d65d 00000007 00000007
[    0.644578] 1f80: c062d15d c0399955 00000000 00000000 c0399955 00000000 00000000 00000000
[    0.653128] 1fa0: 00000000 c039995b 00000000 c000c5f9 00000000 00000000 00000000 00000000
[    0.661677] 1fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    0.670227] 1fe0: 00000000 00000000 00000000 00000000 00000013 00000000 fe75e5cd a7652d8e
[    0.678808] [<c0250e16>] (cpsw_probe+0x3ee/0x88c) from [<c0201597>] (platform_drv_probe+0xd/0xe)
[    0.688005] [<c0201597>] (platform_drv_probe+0xd/0xe) from [<c0200b37>] (driver_probe_device+0x77/0x154)
[    0.697923] [<c0200b37>] (driver_probe_device+0x77/0x154) from [<c0200c45>] (__driver_attach+0x31/0x44)
[    0.707750] [<c0200c45>] (__driver_attach+0x31/0x44) from [<c01ffd5f>] (bus_for_each_dev+0x27/0x44)
[    0.717215] [<c01ffd5f>] (bus_for_each_dev+0x27/0x44) from [<c02005d1>] (bus_add_driver+0x65/0x158)
[    0.726678] [<c02005d1>] (bus_add_driver+0x65/0x158) from [<c0201025>] (driver_register+0x4d/0xac)
[    0.736052] [<c0201025>] (driver_register+0x4d/0xac) from [<c0008661>] (do_one_initcall+0x65/0xf0)
[    0.745429] [<c0008661>] (do_one_initcall+0x65/0xf0) from [<c062d65d>] (kernel_init_freeable+0xb9/0x14c)
[    0.755352] [<c062d65d>] (kernel_init_freeable+0xb9/0x14c) from [<c039995b>] (kernel_init+0x7/0x90)
[    0.764821] [<c039995b>] (kernel_init+0x7/0x90) from [<c000c5f9>] (ret_from_fork+0x11/0x38)
[    0.773554] Code: fe26 e208 f8c4 05c0 (6803) f44f 
[    0.778565] ---[ end trace 3b1325c5f0465841 ]---
[    0.783690] mmc1: BKOPS_EN bit is not set
[    0.787989] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[    0.787989] 
[    0.797540] drm_kms_helper: panic occurred, switching back to text console

At first we got all four LEDs on, then only LED 2 stays on, and kernel doesn't boot.
Could you help to determine where the problem is and whether it can be fixed?

**Comment by jadonk** [comment]
Is this still an issue?
